#include <iostream>
#include "SerialCommunication/SerialPc.cpp"

using namespace std;

// Variables generated by the compiler
short a;
int b;
int c;

// Pointers generated by the compiler
int *integers[3] = {&a, &b, &c};


int main() {
    Arduino arduino = Arduino();
    arduino.analogRead(0, &a);
    if(a > 3) {
        int i = 0;
    }
    cout << i << endl;

}