#include <iostream>
#include "SerialCommunication/SerialPc.cpp"

using namespace std;

// Variables generated by the compiler
int a;
int b;
int c;

// Pointers generated by the compiler
int* integers[3] = {&a, &b, &c};


void listener(Serial *SP, Arduino *arduino) {
    while(true){

    }
}

int main() {
    Arduino arduino = Arduino(listener);

    int a = 1;
    if(10 < a < 20){
        cout << "Hello World";
    }
    cout << int(char(a)) << endl;
    return 0;

}