#include <iostream>
#include "SerialCommunication/SerialPc.cpp"

using namespace std;

// Variables generated by the compiler
int a;
int b;
int c;

// Pointers generated by the compiler
int *integers[3] = {&a, &b, &c};


int main() {
    Arduino arduino = Arduino();
}